services:
  sglang:
    image: ${SGLANG_IMAGE}
    container_name: sglang
    volumes:
      - ${MODEL_DIRPATH}:/data/llms
    restart: always
    environment:
      MODEL_DIRPATH: ${MODEL_DIRPATH}
      MODEL_FNAME: ${MODEL_FNAME}
    entrypoint: python3 -m sglang.launch_server
    command: 
      --model-path /data/llms/${MODEL_FNAME}
      --host 0.0.0.0
      --port 31013
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: "8gb"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:31013/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
  openwebui:
    image: ${OPENWEBUI_IMAGE}
    container_name: openwebui
    volumes:
      - open-webui:/app/backend/data
    restart: always
    ports:
      - ${OPENWEBUI_PORT}:8080
    environment:
      - ENV=dev
    depends_on:
      - sglang
volumes:
  open-webui:
    name: "open-webui"

